---
- name: Uninstall ACoreOs Master
  hosts: acoreos_control_plane
  gather_facts: false
  become: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: Uninstall ACoreOs Master
      shell: |
        echo "1. Stop and remove containers"
        echo "Stop and remove cos-worknode"
        docker rm -f cos-worknode > /dev/null
        echo "2. Remove images"
        docker rmi $(docker images | grep cos | awk '{print $1":"$2}')
        echo "3. Remove tools&configs"
        rm -rf /opt/cni
        rm -rf ~/.kube
      args:
        executable: /bin/bash
      register: clusterinfo
      retries: 5
      delay: 30
      until: clusterinfo.rc == 0
    - debug: var=clusterinfo.stdout_lines
